# Generated by Django 4.2.4 on 2023-09-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', models.TextField()),
                ('date_of_visit', models.DateField()),
                ('time_of_visit', models.TimeField()),
                ('priority_level', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=100)),
                ('date_reported', models.DateField()),
                ('date_resolved', models.DateField()),
                ('nature_of_work', models.TextField()),
                ('action_required_status', models.TextField()),
                ('client_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_staff_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('organization_department', models.CharField(max_length=100)),
                ('primary_personell', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('VisitRequestDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_pass.VisitRequestDetail')),
            ],
        ),
    ]
