# Generated by Django 4.2.4 on 2024-02-14 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_pass', '0002_visitrequestdetail_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequestdetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequestdetail',
            name='comments_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
