# Generated by Django 4.2.4 on 2024-02-14 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access_pass', '0003_alter_visitrequestdetail_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequestdetail',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
