# Generated by Django 4.2.4 on 2024-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_pass', '0006_user_is_manager_user_is_officer_user_is_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneldetail',
            name='equipment_to_be_authorized',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequestdetail',
            name='date_of_visit',
            field=models.DateField(default='2024-10-09'),
        ),
        migrations.AlterField(
            model_name='visitrequestdetail',
            name='time_of_visit',
            field=models.TimeField(default='08:50'),
        ),
    ]
