# Generated by Django 4.2.4 on 2024-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_pass', '0007_personneldetail_equipment_to_be_authorized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequestdetail',
            name='time_of_visit',
            field=models.TimeField(default='09:52'),
        ),
    ]
